apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  PORT: {{ .Values.app.port | quote }}
