apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
type: Opaque
stringData:
  POSTGRES_PASSWORD: "apppassword"
  DATABASE_URL: "postgresql://appuser:apppassword@db:5432/appdb"
