postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  service:
    Port: 5432
  db: appdb
  user: appuser
  password: apppassword

app:
  port: "4000"
  databaseUrl: "postgresql://appuser:apppassword@postgres:5432/appdb"