name: devops_prep

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1

      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Docker Image
        run: docker build -t backend:${{ github.sha }} ./backend

      - name: Build Frontend Docker Image
        run: docker build -t frontend:${{ github.sha }} ./frontend

      - name: Tag Backend Docker Image
        run: docker tag backend:${{github.sha }} ${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}

      - name: Tag Frontend Docker Image
        run: docker tag frontend:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}

      - name: Show Docker Images
        run: docker images

      - name: Push backend Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}

      - name: Push frontend Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}
