name: Infra CI

on:
  push:
    branches:
      - main
    paths:
      - "infra/environments/**"
      - "infra/modules/**"
      - ".github/workflows/infra-ci.yml"
  pull_request:
    paths:
      - "infra/environments/**"
      - "infra/modules/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  s3-check:
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environments/dev/s3
      do_apply: false
    secrets: inherit

  backend-setup:
    needs: s3-check
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environments/dev/s3
      do_apply: true
    secrets: inherit

  vpc-apply:
    needs: backend-setup
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environments/dev/vpc
      do_apply: true
    secrets: inherit

  iam-apply:
    needs: backend-setup
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environments/dev/iam
      do_apply: true
    secrets: inherit

  ecr-apply:
    needs: backend-setup
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environments/dev/ecr
      do_apply: true
    secrets: inherit

  eks-apply:
    needs: [backend-setup, vpc-apply, iam-apply]
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environments/dev/eks
      do_apply: true
    secrets: inherit
