name: Infra CI

on:
  push:
    branches:
      - main
    paths:
      - "infra/environment/**"
      - "infra/modules/**"
      - ".github/workflows/infra-ci.yml"
  pull_request:
    paths:
      - "infra/environment/**"
      - "infra/modules/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  s3-check:
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environment/dev/s3
      do_apply: false
    secrets: inherit

  backend-setup:
    needs: s3-check
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environment/dev/s3
      do_apply: true
    secrets: inherit

  ecr-apply:
    needs: backend-setup
    uses: ./.github/workflows/infra-reusable-ci.yml
    with:
      module_path: infra/environment/dev/ecr
      do_apply: true
    secrets: inherit

        